### ISSUE TITLE
Errors reported by other mods

### ISSUE THREAD

**Issue by phmalacher** [Bilka2/AbandonedRuins#17]
Disco science reports a lab from this mod is not registered properly
Water as a resource reports pumps from this mod don't have a last player set

weird you don't allow discussions on the mod page, makes no wonder you get few bugs reports ...

**Comment by Bilka2** [comment]
Hey, "Water As A Resource" was changed by the mod author so the mods should work together now, see https://mods.factorio.com/mod/WaterAsAResource/discussion/6057ad64c17e1a54a5a5ec87.
For "Disco Science", I contacted the mod author to work on making the mods compatible, further conversation about this will happen there: https://github.com/danielbrauer/DiscoScience/issues/6
