### ISSUE TITLE
Ruins as only source of things

### ISSUE THREAD

**Issue by warmist** [Bilka2/AbandonedRuins#21]
Add some new material and/or processes to the tech tree without a way to construct the buildings needed for them. This would simulate a "lost technology" or "alien materials" etc. The only way to use it would be to build a base around those special ruins. 

The intent would be to make exploration necessary for advancement and adding those ruins to the logistics of the existing base.

**Comment by Bilka2** [comment]
I am not interested in adding this to the mod.
