### ISSUE TITLE
Feature Request: Disable ruins in the internal layers

### ISSUE THREAD

**Issue by USSX-Hares** [Bilka2/AbandonedRuins#27]
Hi

I am using a [The Blueprint Designer Lab](https://mods.factorio.com/mod/BlueprintLab_design) module which uses its internal layer.
I then installed the Runis mod and almost the entire Lab area is now covered in ruins:

![Lab map -- normally](https://user-images.githubusercontent.com/29100587/164502816-843b3b35-7cfa-442b-9e7c-b9792a1cc65e.png)
![Lab map -- with ruins](https://user-images.githubusercontent.com/29100587/164502982-09bbac46-47d8-4dee-84ca-dc49bab2aadb.png)
![Ruins inside Lab](https://user-images.githubusercontent.com/29100587/164503054-ab470870-544c-401e-8329-b318d717b10e.png)

**Comment by Bilka2** [comment]
The blueprint lab mod can exclude its surface via the remote functions of this mod: https://github.com/Bilka2/AbandonedRuins/blob/master/control.lua#L162-L169

If the other mod isn't actively maintained I might look into hardcoding it on my side, but I'd rather not. Not like I actively maintain this mod either lol
