### ISSUE TITLE
Crashes on Load-in with Factory Inspector

### ISSUE THREAD

**Issue by ErisAnn** [Bilka2/AbandonedRuins#29]
If I have the Factory Inspector mod enabled, I consistently crash on load-in with the error below.

Thank you for your time!!

---

The mod The Ruins Mod (1.1.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event AbandonedRuins::on_tick (ID 0)
The mod Factory Inspector (1.1.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-inspector::script_raised_built (ID 79)
__factory-inspector__/script/event-handlers.lua:7: attempt to index field 'created_entity' (a nil value)
stack traceback:
	__factory-inspector__/script/event-handlers.lua:7: in function <__factory-inspector__/script/event-handlers.lua:6>
stack traceback:
	[C]: in function 'create_entity'
	__AbandonedRuins__/spawning.lua:45: in function 'spawn_entity'
	__AbandonedRuins__/spawning.lua:94: in function 'spawn_entities'
	__AbandonedRuins__/spawning.lua:172: in function 'spawn_ruin'
	__AbandonedRuins__/spawning.lua:184: in function 'spawn_random_ruin'
	__AbandonedRuins__/control.lua:58: in function <__AbandonedRuins__/control.lua:53>

---

![image](https://user-images.githubusercontent.com/29384501/184952927-575b9286-870d-47b1-9701-53908106870f.png)

---

Edit: Forgot to include full mod list for troubleshooting in case it isn't the Factory Inspector's fault:
https://i.imgur.com/m8nRZFp.png

**Comment by Bilka2** [comment]
Hey, this is a bug in the factory inspector mod. There is already a pull request with a solution: https://github.com/Aurensar/factorio-factoryinspector/pull/1. You could locally apply those changes to factory inspector to continue playing with both mods.

**Comment by ErisAnn** [comment]
> Hey, this is a bug in the factory inspector mod. There is already a pull request with a solution: [Aurensar/factorio-factoryinspector#1](https://github.com/Aurensar/factorio-factoryinspector/pull/1). You could locally apply those changes to factory inspector to continue playing with both mods.

omg I love you; I'm sorry I didn't see it.  Thank you for the quick reply!!

**Comment by jocker-il** [comment]
seems it is still pending inclusion since december '23, not sure if the author of FactoryInspector even noticed it, but it's now incompatible with his latest build (1.1.25) and no mention of "AbandonedRuins" in the changelog.txt...

![image](https://github.com/user-attachments/assets/9128ed0a-a0b4-44cf-be27-dc02bd425db4)

**Comment by Bilka2** [comment]
There is no factory inspector 1.1.25 on the mod portal or on github, where are you getting the build from?

**Comment by Bilka2** [comment]
In fact, looking at the factory inspector code on github, it should work without problems in 1.1.24: https://github.com/Aurensar/factorio-factoryinspector/blob/b8fff2c39169a65b8dd5138cacdecf9b0143ea79/script/event-handlers.lua#L7

**Comment by jocker-il** [comment]
I saw a reference to 1.1.25 in the change log,

 I can't program that well so I guess he fixed it, if you say it's ok - you're the expert, an ex-Wube employee, if I'm not mistaken ?

**Comment by Bilka2** [comment]
Hey, as I said based on the code on github, factory inspector 1.1.24 should work. If there is a problem with that version of the mod or a newer version of it, please link the version and the give error.

(I am still a Wube employee.)
