### ISSUE TITLE
Error with RealisticReactors

### ISSUE THREAD

**Issue by ErisAnn** [Bilka2/AbandonedRuins#32]
I'm pretty sure this is RealisticReactors' fault and already reported it on their mod page, but they don't seem very responsive, so I thought I'd report it to you also just in case you knew of the solution, because choosing between these is hard for me.  Sorry if I'm wasting your time.  Thank you for all your efforts.

The mod The Ruins Mod (1.1.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event AbandonedRuins::on_tick (ID 0)
The mod Realistic Reactors (3.1.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RealisticReactors::script_raised_built (ID 79)
RealisticReactors/scripts/heat/buffer.lua:64: attempt to perform arithmetic on field 'y' (a nil value)
stack traceback:
RealisticReactors/scripts/heat/buffer.lua:64: in function 'vecadd'
RealisticReactors/scripts/heat/buffer.lua:69: in function 'for iterator'
RealisticReactors/scripts/heat/network.lua:488: in function 'add_entity_to_network_cell'
RealisticReactors/scripts/heat/network.lua:618: in function 'add_heat_pipe'
RealisticReactors/scripts/events/construct.lua:35: in function 'on_heatpipe_added'
RealisticReactors/scripts/events/construct.lua:104: in function 'entity'
RealisticReactors/control.lua:51: in function <RealisticReactors/control.lua:50>
stack traceback:
[C]: in function 'create_entity'
AbandonedRuins/spawning.lua:45: in function 'spawn_entity'
AbandonedRuins/spawning.lua:94: in function 'spawn_entities'
AbandonedRuins/spawning.lua:172: in function 'spawn_ruin'
AbandonedRuins/spawning.lua:184: in function 'spawn_random_ruin'
AbandonedRuins/control.lua:58: in function <AbandonedRuins/control.lua:53>

**Comment by Bilka2** [comment]
Yeah, that looks like RealisticReactors problem, it's just happening within the create event of the ruins mod placing heat pipes. I don't know a solution for the RealisticReactors mod, it's not as simple as the Factory Inspector crash.

**Comment by ErisAnn** [comment]
> Yeah, that looks like RealisticReactors problem, it's just happening within the create event of the ruins mod placing heat pipes. I don't know a solution for the RealisticReactors mod, it's not as simple as the Factory Inspector crash.

rip, thanks for taking a look at it.  ily <3
