### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xXmilchzombieXx** [Bilka2/AbandonedRuins#34]
I have the bug that I cant claim ruins to dismantle them.

**Comment by Bilka2** [comment]
Please provide more information. For example, is it all ruins or only some entities, what other mods are you running, is it the same in a new save, etc.

**Comment by xXmilchzombieXx** [comment]
Is it possible to make a list with all the mods that I am using? Its different sometimes there are entities that are not built from enemies so I can dismantle them without any problem but sometimes I cant. The most entities that I cant dismantle are turrets and steammachines.

**Comment by Bilka2** [comment]
It's expected that some turrets are hostile and cannot be deconstructed.

For steam engines there shouldn't be any hostile ones, you should be able to claim and then deconstruct or mine them. The best way to check the steam engine issue would be if you could provide a save file where you stand next to the steam engines that you can't claim.

**Comment by xXmilchzombieXx** [comment]
It could be that this bug is from the addon mod for realistic ruins and I will send a savegame if I find it again.

**Comment by xXmilchzombieXx** [comment]
[MyWorld.zip](https://github.com/Bilka2/AbandonedRuins/files/10951588/MyWorld.zip)
Here I am standing beside a traintrack that I cant dismantle but I dont know if it should work or not.

**Comment by xXmilchzombieXx** [comment]
And here is the steam engine that I cant dismantle. 
[MyWorld.zip](https://github.com/Bilka2/AbandonedRuins/files/10951601/MyWorld.zip)

**Comment by Bilka2** [comment]
Thanks for the save file. Those ruins are indeed from realistic ruins. You'll have to report the bug on that mod, it should not be spawning normal entities on the enemy force.

If you want to fix your save and don't mind disabling achievements, you can use the map editor to change the force of the entities. Open the map editor with `/editor` in chat, click on the force tab, click on the change force tab and select the entities. You can use `/editor` again to leave the map editor.
